[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
client = { workspace = true }
shared = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
leptos_axum = { workspace = true }
leptos = { workspace = true, features = ["ssr"] }
leptos_meta = { workspace = true, features = ["ssr"] }
leptos_router = { workspace = true, features = ["ssr"] }
tower-http = { workspace = true, features = [
    "compression-gzip",
    "compression-br",
] }
